# /etc/puppet/manifest/site.pp
include nginx
#include mysql
include gcc
include cmake
#include hiawatha
include smartmontools
include iftop
#include postgresql
include nagios
include postfix
include psad
