#Required
name    'fmacias-hiawatha'
version '0.0.1'
source 'https://github.com/fmaciask/puppet/tree/master/modules/hiawatha'
author 'fmacias'
license 'Hiawatha License'
summary 'Manages the installation of Hiawatha webserver and runs the service'
description 'Hiawatha webserver'
